### ISSUE TITLE
On install: socket.error: [Errno 111] Connection refused 

### ISSUE THREAD

**Issue by shan3k** [litecoin-foundation/LitecoinNode#1]
Not sure what this is. Off the top of my head maybe default firewall config or something? 
I'll continue with rebooting the box now and see what happens.

`
Add the node status script to cron and run it every 10 minutes
no crontab for root
Add the distributions website dir to the litecoin-nodes-status.py script
Add Litecoin rpc user and password to the litecoin-nodes-tatus.py script
Traceback (most recent call last):
  File "/home/litecoind/scripts/litecoin-node-status.py", line 12, in <module>
    lcd_data = get_lcd_info.getinfo()
  File "/usr/local/lib/python2.7/dist-packages/bitcoinrpc/authproxy.py", line 112, in __call__
    'Content-type': 'application/json'})
  File "/usr/lib/python2.7/httplib.py", line 1017, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python2.7/httplib.py", line 1051, in _send_request
    self.endheaders(body)
  File "/usr/lib/python2.7/httplib.py", line 1013, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 864, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 826, in send
    self.connect()
  File "/usr/lib/python2.7/httplib.py", line 807, in connect
    self.timeout, self.source_address)
  File "/usr/lib/python2.7/socket.py", line 571, in create_connection
    raise err
socket.error: [Errno 111] Connection refused
removed '/home/litecoind/ubuntu-install-statuspage.sh'
Do you want to create a swap file? (Y/N) Ysocket.error: [Errno 111] Connection refused

removed '/home/litecoind/ubuntu-install.sh'
removed '/home/litecoind/linux-install.sh'
All done! Do you want to reboot? (Y/N)
Attach files by dragging & dropping,  Choose Files selecting them, or pasting from the clipboard.`

**Comment by fromalexx** [comment]
I got the same error on Ubuntu 14.04.5x64, 16.04.3x64, and 17.04x64.

**Comment by fromalexx** [comment]
Also noticed something a little odd.. There was [a typo in the Debian and Raspbian versions](https://github.com/litecoin-foundation/LitecoinNode/pull/5/commits/9a14a0e5d6c2f0f288af6fc44ed5f2e8ca297af9) of install-statuspage.sh, but was correct in the Ubuntu version.

Notice the line `Add Litecoin rpc user and password to the litecoin-nodes-tatus.py script` found in the issue's error log above. It is correct on the Ubuntu script, so it appears the downloader is downloading either Raspbian or Debian installer instead because the typo is there. I did test by forcing the download of the Ubuntu version and still got the same issue as noted above.

Side note: Pull request created to fix typo

**Comment by fromalexx** [comment]
Got the same error on Debian.. Any ideas @losh11 ? Is it possible its something with DigitalOcean since every server I ran was in DigitalOcean?

@shanekillian , Did you run yours in DigitalOcean as well?

**Comment by plwalters** [comment]
I'm running on digital Ocean and Ubuntu without an issue

**Comment by troy-harris-droid** [comment]
Same issue on Ubuntu 16.04. Litecoind failed to start as it expects Upstart and 16.04 is using Systemv. You then get the `socket.error: [Errno 111] Connection refused` from litecoin-nodes-status.py
